### ISSUE TITLE
Added Greedy Solutions

### ISSUE THREAD

**Issue by VedantKhairnar** [DevScript/CP-Solutions#2]

**Comment by Bijay555** [comment]
Hey @VedantKhairnar  Can you assign to me? I will add greedy solution in python

**Comment by ggoel1998** [comment]
Hey @VedantKhairnar  I can add great C++ solutions to greedy problems.

**Comment by VedantKhairnar** [comment]
Sure Feel free to add.
Name the file as PlatformName-QuestionName.extension 
For Example: Hackerrank-MarkAndToys.py

**Comment by ggoel1998** [comment]
two problems added from #8 , adding more soon
cheers!!
