### ISSUE TITLE
Add Search Algo Solutions

### ISSUE THREAD

**Issue by VedantKhairnar** [DevScript/CP-Solutions#3]

**Comment by hackbansu** [comment]
Adding binary search in Java.

**Comment by hackbansu** [comment]
Created #6 for binary search in java. Cheers :)

**Comment by VedantKhairnar** [comment]
Sure Thanks!! : )

**Comment by ArielA147** [comment]
@VedantKhairnar Can I help and add more searching algo ?

**Comment by saitarunmandiga** [comment]
can i add binary search tree(BST)

**Comment by Adithiyan** [comment]
I would like to do this in java.
